services:
  catalogue:
    build: ./catalogue
    image: catalogue:v1

  user:
    build: ./user
    image: user:v1

  cart:
    build: ./cart
    image: cart:v1

  shipping:
    build: ./shipping
    image: shipping:v1

  payment:
    build: ./payment
    image: payment:v1

  mongodb:
    build: ./mongodb
    image: mongodb:v1

  mysql:
    build: ./mysql
    image: mysql:v1

  web:
    build: ./web
    image: web:v1
